# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a3407322b599a4fe4de2dc0accaf8de35770cb9d3d901c260735148282343f5cb60144f9cca3a0cf035dca8ac42c472ce07544a31ef9103bf311cb05657da7

test:
  secret_key_base: a3e826be75e8eb4d8161bcd10549b8f2471a4d35e7168082142f6ba16471db2cb7794cc037897acf68e151578bd8b29eadd367d5b7f9a212144228b160654d85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
